version: '3.8'

services:
  zookeeper1:
    platform: linux/arm64
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka1:
    platform: linux/arm64
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "org.b0102.one.event:1:1,org.b0102.two.event:1:1,org.b0102.three.event:1:1"
    networks:
      - kafka-network

  zookeeper2:
    platform: linux/arm64
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2182"
    networks:
      - kafka-network

  kafka2:
    platform: linux/arm64
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper2
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "org.b0102.one.event:1:1,org.b0102.two.event:1:1,org.b0102.three.event:1:1"
    networks:
      - kafka-network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka1
      - kafka2
    environment:
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: kafka1:9092,kafka2:9092
    networks:
      - kafka-network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka1
      - kafka2
    environment:
      SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS: kafka1:9092,kafka2:9092
    networks:
      - kafka-network

networks:
  kafka-network:
    name: kafka